### ISSUE TITLE
namespace injection not working when using [Inject("some.doted.path")

### ISSUE THREAD

**Issue by joaofernandes** [swiz/swiz-framework#2]
Injector Processor fails to inject a dependency when using a doted path in a namespace scope

Example  
[Inject("myModel.someProp")]
my_namespace var someProp:ISomePropInterface;

it fails at line 300 from injectProcessor >  if( destObject[ destPropName ] is Function )

returning "ReferenceError: Error #1069: Property my_namespace::someProp not found on my.class.with.namespace.injected.model and there is no default value."

replacing my_namespace by public works like a charm as other not doted injections.

**Comment by swiz** [comment]
Hi João,

As I mentioned on the list, bindings cannot be created for custom namespaced members. Property injection creates a binding by default when the source is bindable, so that was the problem.

To avoid this problem in the future, Swiz will no longer attempt to create a binding for custom namespaced members. This change has been implemented in http://github.com/swiz/swiz-framework/commit/b505476bdb7eb75007c119746f723fec4f96db6d.

Ben

**Comment by joaofernandes** [comment]
Thanks, works perfectly now
